feat: add release action
fastify/github-action-merge-dependabot pull request #123
Opened 2021-12-07 15:09 UTC by nuragic

Missing part of #112.

2021-12-07 15:11 UTC, Eomm approved these changes

2021-12-07 15:13 UTC, simoneb commented
perfect. please also link the issue so that it's closed when we merge this PR

2021-12-07 16:44 UTC, nuragic commented
@simoneb I've linked the issue in the commit description

2021-12-07 17:08 UTC, simoneb approved these changes

2021-12-07 17:14 UTC, simoneb requested changes
we can't use this action yet, more details to follow

2021-12-07 17:19 UTC, simoneb commented
I'm blocking this PR because I just recalled that there's something that the release automation action doesn't do for us and we need to decide how to handle it, or this won't do what we expect.

This action has a [build npm script](https://github.com/fastify/github-action-merge-dependabot/blob/main/package.json#L7). This script needs to be executed in order to generate the dist folder which is what is actually being executed when the action runs.

The release automation action does npm install (this thing has a problem in itself because it runs on whatever Node.js version the action runs on, NOT what we would like it to run on, but that's another issue), but it runs no other scripts. Without running the build script, the published released will not contain the changes it would need to contain.

I see 2 options here:

- we enhance the release action to run additional scripts (action-side approach)
- we configure this repo to run the build script on a npm lifecycle script, e.g. prepare or postinstall or whatever makes sense (user-side approach)

2021-12-07 17:26 UTC, simoneb commented
Opened an issue about this in https://github.com/nearform/optic-release-automation-action/issues/27

2021-12-07 17:32 UTC, Eomm commented
> we enhance the release action to run additional scripts (action-side approach)

Just to share that, by default, the GitHub nodejs action template provides you this workflow to check the `dist` build:

https://github.com/Eomm/why-don-t-you-tweet/blob/main/.github/workflows/check-dist.yml

This is a reminder to build the source code actually.

2021-12-07 17:38 UTC, nuragic commented
Great, thanks for the feedback! Given the above, I think it would make sense to go with:
> we enhance the release action to run additional scripts (action-side approach)

Just a question aside, why we compile everything via `ncc`?

2021-12-07 17:42 UTC, simoneb commented
> Just a question aside, why we compile everything via `ncc`?

The action needs to be self contained, so either we commit node_modules or we bundle it. This second approach is also what's recommended in https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github.

In fact, we should probably we doing the same for the release action! I'll create an issue.

2021-12-07 18:11 UTC, nuragic commented
Oh thanks for the link!

> Checking in your node_modules directory can cause problems. As an alternative, you can use a tool called @vercel/ncc to compile your code and modules into one file used for distribution.

👍

2021-12-08 11:19 UTC, simoneb commented
There's one more thing that we have to do before we go ahead with this PR. We first need to release a new version capable of automerging semver-like. So we should keep doing manual releases until https://github.com/fastify/github-action-merge-dependabot/issues/124 is released.

2021-12-09 11:00 UTC, nuragic commented
@simoneb now that #124 is released, should we unblock this PR?

2021-12-09 11:06 UTC, simoneb commented
@nuragic no but thanks for bringing it up because the dependency was not explicit. We also depend on https://github.com/nearform/optic-release-automation-action/issues/27

2021-12-10 14:50 UTC, simoneb commented
@nuragic @Eomm is there a chance that in fact we're already good here?

See https://github.com/fastify/github-action-merge-dependabot/blob/main/.husky/pre-commit

2021-12-10 18:22 UTC, Eomm commented
I don't think we have done here: the local hooks can be skipped and a malicious user may manipulate the `dist/` build (who is reading that file)

When we will release this PR https://github.com/nearform/optic-release-automation-action/pull/30 we are ready to go here.
The actual `optic-release-automation-action` version runs the `actions/checkout@v2.4.0` step every time overwriting whatever build the user made before.. so those PR's changes are necessary to let the GHA environment build a secure `dist/` payload

2021-12-16 09:37 UTC, Eomm requested changes

2021-12-16 09:37 UTC, Eomm commented on .github/workflows/release.yml
> +    steps:
```suggestion
    steps:
      - name: Setting action build runtime
        uses: actions/setup-node@v2
        with:
          node-version: 16
```

2021-12-16 09:37 UTC, Eomm commented on .github/workflows/release.yml
> +      - uses: nearform/optic-release-automation-action@v2.3.0
```suggestion
      - uses: nearform/optic-release-automation-action@v2
```

2021-12-16 09:37 UTC, Eomm commented on .github/workflows/release.yml
> +          sync-semver-tags: true
```suggestion
          sync-semver-tags: true
          build-command: |
            echo 'installing husky hooks..'
            npm ci

```

2021-12-16 10:11 UTC, Eomm approved these changes

2021-12-18 16:57 UTC, simoneb approved these changes

2021-12-20 15:34 UTC, merged