"any" value added to target option
fastify/github-action-merge-dependabot pull request #99
Opened 2021-11-11 07:08 UTC by sameer-coder

The target value can be one of the `major, premajor, minor, preminor, patch, prepatch or prerelease`. This PR adds another value `any` which can be used to run the action without any semver version checks.

Documentation has been updated

Closes #95

2021-11-11 08:37 UTC, simoneb reviewed
Shall we make any the new default?

2021-11-11 08:37 UTC, simoneb commented on src/index.js
> +    if (TARGET !== 'any') {
let's use the constants

2021-11-11 08:53 UTC, sameer-coder commented
yeah I think `any` as the new default makes more sense

2021-11-12 08:58 UTC, sameer-coder commented
@simoneb is this PR good to merge? I had updated the test cases.

2021-11-12 09:06 UTC, simoneb requested changes
They way you updated the tests doesn't look right, the structure of the nested tests specifically. Please have a look

2021-11-12 09:38 UTC, sameer-coder commented
> They way you updated the tests doesn't look right, the structure of the nested tests specifically. Please have a look

The nested tests were already there. I have eliminated the nesting and improved the structure now.

2021-11-12 09:43 UTC, simoneb approved these changes
The nesting made sense, it just didn't make much sense after you had changed it.

It made sense because previously we returned major when:

- major was provided
- input was not recognized

With your change "any" would have got the same behavior as major had previously but you didn't update the structure of the tests accordingly.

Without nesting the problem does not exist in the first place so we're good

2021-11-18 10:51 UTC, merged